name: nodered
services:
  node-red:
    container_name: node-red
    environment:
      TZ: America/Mazatlan
    image: nodered/node-red:latest
    labels:
      traefik.enable: "true"
      traefik.http.routers.node-red.entrypoints: websecure
      traefik.http.routers.node-red.rule: Host(`nodered-ITC.duckdns.org`)
      traefik.http.routers.node-red.tls: "true"
      traefik.http.routers.node-red.tls.certresolver: lets-encrypt
      traefik.http.services.node-red.loadbalancer.server.port: "1880"
    networks:
      iotnetwork: null
      node-red-net: null
    ports:
      - mode: ingress
        target: 1880
        published: "1880"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/nodered/nodered_data
        target: /data
        bind: {}
networks:
  iotnetwork:
    name: iotnetwork
    external: true
  node-red-net:
    name: nodered_node-red-net
